const frases = {
  triste: [ "Está bien sentir tristeza, es parte de sanar.",
  "Cada lágrima es un paso hacia la paz interior.",
  "Permítete sentir, no reprimas tus emociones.",
  "La tristeza no es debilidad, es humanidad.",
  "Después de la tormenta, siempre llega la calma.",
  "Tu dolor es válido y merece ser escuchado.",
  "No estás solo/a en tus momentos difíciles.",
  "Cada día trae nuevas oportunidades para sanar.",
  "La tristeza es un puente hacia la esperanza.",
  "El tiempo ayuda a suavizar el dolor.",
  "Permítete descansar y recuperar fuerzas.",
  "La sanación comienza cuando aceptas lo que sientes.",
  "Eres más fuerte de lo que crees.",
  "La tristeza también enseña y transforma.",
  "Busca apoyo cuando lo necesites, no estás solo/a.",
  "El amor propio es esencial para superar la tristeza.",
  "Hablar de tus sentimientos libera y sana.",
  "Cada pequeño avance es un gran logro.",
  "No te castigues por sentir tristeza.",
  "La tristeza abre la puerta a nuevas alegrías.",
  "Cuida de ti mismo con paciencia y cariño.",
  "El silencio a veces es necesario para sanar.",
  "Confía en que la luz volverá a tu vida.",
  "Las lágrimas son semillas de esperanza.",
  "Permítete tiempo para sanar a tu ritmo.",
  "La tristeza no dura para siempre.",
  "Eres digno/a de amor y comprensión.",
  "El dolor puede ser el inicio de un nuevo camino.",
  "Respira hondo y date permiso para sentir.",
  "Tu corazón sabe cómo recuperarse.",
  "Busca la belleza incluso en los días grises.",
  "Cada experiencia te fortalece y enseña.",
  "La tristeza no define tu valor.",
  "El amor y la esperanza siempre están presentes.",
  "Cuida tu mente y cuerpo con amor.",
  "El apoyo de otros puede ser un gran alivio.",
  "No te rindas, la vida tiene mucho para ofrecerte.",
  "La tristeza es parte del ciclo de la vida.",
  "Cada día es una oportunidad para comenzar de nuevo.",
  "Permítete momentos de alegría cuando puedas.",
  "La tristeza puede abrir caminos a la empatía.",
  "Eres valiente por enfrentar tus emociones.",
  "La paciencia es clave para la sanación.",
  "Nunca pierdas la esperanza en ti mismo/a.",
  "El amor propio te ayudará a salir adelante.",
  "Cada paso que das es un triunfo.",
  "Confía en tu proceso de recuperación.",
  "La tristeza puede transformarse en crecimiento.",
  "Rodéate de luz y amor.",
  "Tu historia aún tiene capítulos felices por venir.",
  "Sigue adelante, lo mejor está por llegar."],
  feliz: ["Tu alegría es contagiosa y poderosa.",
  "Disfruta cada momento de felicidad que te regala la vida.",
  "La felicidad está en las pequeñas cosas del día a día.",
  "Sonríe, porque la vida es hermosa cuando decides verla así.",
  "Celebra tus logros y las pequeñas victorias.",
  "La felicidad es un estado que se cultiva a diario.",
  "Tu sonrisa ilumina el mundo a tu alrededor.",
  "La alegría auténtica nace del amor propio.",
  "Haz más de lo que te hace feliz cada día.",
  "La felicidad está en la gratitud por lo que tienes.",
  "Eres merecedor/a de momentos felices y paz interior.",
  "Disfruta el presente y deja que la felicidad fluya.",
  "El buen ánimo es un regalo que puedes darte a ti mismo.",
  "La felicidad crece cuando la compartes con otros.",
  "Encuentra alegría en las cosas simples y bellas.",
  "Tu bienestar es la base de tu felicidad.",
  "La alegría fortalece el cuerpo y el alma.",
  "Sonríe sin motivo, solo porque puedes.",
  "Cada día es una nueva oportunidad para ser feliz.",
  "La felicidad se encuentra en el amor y la paz interior.",
  "Vive con pasión y entusiasmo.",
  "La felicidad está en tu actitud ante la vida.",
  "Que tu alegría inspire a quienes te rodean.",
  "Disfruta de la vida con el corazón abierto.",
  "La sonrisa es el lenguaje universal de la felicidad.",
  "La alegría es el combustible del alma.",
  "Encuentra razones para ser feliz cada día.",
  "La felicidad es un viaje, no un destino.",
  "La risa es medicina para el alma.",
  "El amor propio es la clave para la verdadera felicidad.",
  "La alegría está en los momentos compartidos.",
  "Agradece cada instante que te hace sonreír.",
  "Vive con gratitud y alegría profunda.",
  "La felicidad nace de la paz interior.",
  "Cada día es un regalo lleno de posibilidades felices.",
  "La sonrisa puede cambiar tu día y el de otros.",
  "La alegría te hace invencible ante los retos.",
  "Siente la felicidad en cada respiración.",
  "La felicidad florece cuando eliges ser positivo.",
  "Celebra la vida y sus maravillosos detalles.",
  "El corazón feliz atrae cosas buenas.",
  "La alegría se multiplica cuando se comparte.",
  "Disfruta el momento y sé feliz ahora.",
  "La felicidad verdadera viene de dentro de ti.",
  "Que tu luz interior brille con felicidad.",
  "Cada sonrisa abre puertas a nuevas oportunidades.",
  "Encuentra felicidad en tus pasiones y sueños.",
  "Vive con un espíritu alegre y agradecido.",
  "La felicidad es tu derecho natural.",
  "Disfruta la vida con amor y felicidad."],
  miedo: ["El miedo es solo una señal para avanzar con más fuerza.",
  "Atrévete a enfrentar tus miedos, crecerás.",
  "La valentía no es ausencia de miedo, es actuar a pesar de él.",
  "Cada miedo superado es un triunfo personal.",
  "No dejes que el miedo te detenga, eres más fuerte.",
  "El miedo es una oportunidad para demostrar tu coraje.",
  "Enfrenta lo que temes y descubrirás tu poder.",
  "El miedo puede ser el comienzo de tu libertad.",
  "No permitas que el miedo controle tu vida.",
  "La valentía nace cuando decides no rendirte.",
  "Cada paso con miedo es un paso hacia tu crecimiento.",
  "Confía en ti, el miedo es solo un obstáculo temporal.",
  "Superar el miedo abre puertas a nuevas experiencias.",
  "Tu fuerza interior es más grande que cualquier miedo.",
  "No estás solo, el miedo es parte del camino.",
  "El miedo puede enseñarte a ser más valiente.",
  "A veces el mayor acto de valentía es intentarlo.",
  "Tu corazón es más fuerte que cualquier temor.",
  "El miedo es solo un pensamiento, no una realidad.",
  "Atrévete a soñar a pesar del miedo.",
  "No huyas del miedo, acompáñalo y supéralo.",
  "Cada miedo vencido fortalece tu alma.",
  "La luz siempre vence a la oscuridad del miedo.",
  "El miedo es pasajero, el coraje es para siempre.",
  "Sé valiente y sigue adelante.",
  "El miedo limita, la acción libera.",
  "No dejes que el miedo te robe tus sueños.",
  "La valentía es la clave para la libertad personal.",
  "Enfrentar el miedo te lleva a la grandeza.",
  "Confía en tu capacidad para superar cualquier miedo.",
  "El miedo es el inicio de una nueva aventura.",
  "Tu fuerza interior es invencible.",
  "No temas equivocarte, eso también es crecer.",
  "Cada desafío superado te hace más fuerte.",
  "El miedo es el maestro de la valentía.",
  "No permitas que el miedo te paralice.",
  "Cree en ti y el miedo disminuirá.",
  "La valentía se practica cada día.",
  "El miedo no define quién eres.",
  "Sé audaz y conquista tus miedos.",
  "El miedo es solo un límite temporal.",
  "No te rindas por miedo, sigue adelante.",
  "Tu coraje inspira a otros.",
  "Cada pequeño acto valiente suma mucho.",
  "Enfrentar el miedo es un acto de amor propio.",
  "No temas al miedo, teme no intentarlo.",
  "Eres capaz de cosas increíbles más allá del miedo.",
  "El miedo no es el final, es solo el principio.",
  "Sé fuerte, valiente y persistente."],
  sorpresa: ["La vida está llena de momentos inesperados y maravillosos.",
  "Cada sorpresa es una puerta a nuevas oportunidades.",
  "Abre tu mente y déjate asombrar por lo inesperado.",
  "La magia ocurre cuando menos lo esperas.",
  "El asombro es el motor de la curiosidad y el crecimiento.",
  "Las mejores historias empiezan con una sorpresa.",
  "Cada día trae algo nuevo para descubrir.",
  "Sorpréndete a ti mismo con lo que puedes lograr.",
  "La vida es un regalo lleno de momentos sorprendentes.",
  "La sorpresa abre caminos a la creatividad.",
  "Nunca subestimes el poder de lo inesperado.",
  "Deja que la maravilla te inspire y motive.",
  "La sorpresa es la chispa que enciende la pasión.",
  "Cada instante puede ser un descubrimiento.",
  "La sorpresa te invita a salir de tu zona de confort.",
  "El asombro renueva el espíritu y la mente.",
  "Sorprenderse es vivir con ojos de niño.",
  "Cada sorpresa te acerca a la alegría auténtica.",
  "La vida es una aventura llena de misterios maravillosos.",
  "Disfruta cada momento inesperado como un regalo.",
  "La sorpresa puede transformar tu perspectiva.",
  "Abre tu corazón a lo que no esperabas.",
  "Las sorpresas son oportunidades disfrazadas.",
  "El asombro es la puerta al aprendizaje profundo.",
  "Sorpréndete y déjate llevar por la maravilla.",
  "Cada día puede traer una nueva razón para sonreír.",
  "Lo inesperado a menudo es lo más valioso.",
  "La sorpresa es un llamado a la atención plena.",
  "Mantén viva la curiosidad y el asombro.",
  "La vida sorprende a quienes están abiertos a ella.",
  "Deja que la sorpresa te impulse a crecer.",
  "El asombro conecta el alma con la belleza del mundo.",
  "Cada sorpresa es un recordatorio de la magia de la vida.",
  "Sorpréndete y agradece lo inesperado.",
  "La sorpresa rompe la monotonía y despierta la pasión.",
  "Permítete maravillar y sentir asombro.",
  "Cada sorpresa es una invitación a la alegría.",
  "La vida se renueva con cada momento inesperado.",
  "Abraza la sorpresa como parte de tu viaje.",
  "La maravilla te conecta con lo esencial.",
  "Las sorpresas son regalos del universo para ti.",
  "El asombro es el lenguaje del corazón abierto.",
  "Sorpréndete y déjate inspirar cada día.",
  "Cada instante inesperado tiene un propósito.",
  "La vida es mejor cuando te sorprendes con ella.",
  "La sorpresa despierta la creatividad y el entusiasmo.",
  "Abre tu mente para recibir lo nuevo.",
  "La magia está en los detalles que no esperas.",
  "Disfruta del misterio y la sorpresa constante."],
  estresado: [ "Cada hora de estudio es una inversión en tu futuro.",
    "El esfuerzo constante te llevará lejos.",
    "No te rindas, el conocimiento es poder.",
    "Cada desafío académico fortalece tu mente.",
    "Aprender es el camino hacia tus sueños.",
    "Confía en tu capacidad de superar obstáculos.",
    "La disciplina es la llave del éxito.",
    "Cada pequeño logro cuenta y suma.",
    "No temas equivocarte, de los errores se aprende.",
    "El estudio abre puertas a nuevas oportunidades.",
    "Tu dedicación tiene un gran valor.",
    "Sigue adelante, la meta está cerca.",
    "El conocimiento transforma tu vida.",
    "La paciencia y la constancia son tus aliados.",
    "No dejes que las dudas te detengan.",
    "Tu esfuerzo hoy es tu premio mañana.",
    "Aprender es crecer y avanzar.",
    "Cada día es una nueva oportunidad para aprender.",
    "Los retos académicos te preparan para la vida.",
    "Confía en el proceso y en ti mismo.",
    "No te compares, cada uno tiene su ritmo.",
    "El estudio constante trae grandes recompensas.",
    "Tú tienes la capacidad de lograrlo.",
    "La motivación te ayudará a superar obstáculos.",
    "Estudia con pasión y dedicación.",
    "Cada concepto aprendido es una victoria.",
    "La educación es tu mejor herramienta.",
    "No te desanimes por las dificultades.",
    "Tu futuro depende de lo que haces hoy.",
    "El esfuerzo siempre tiene su recompensa.",
    "Los sueños se construyen con estudio y trabajo.",
    "Tu mente es poderosa, aliméntala con conocimiento.",
    "Cada examen es una oportunidad para demostrar tu esfuerzo.",
    "Mantén el enfoque y la disciplina.",
    "El aprendizaje es un camino continuo.",
    "La curiosidad te llevará lejos.",
    "No temas pedir ayuda cuando la necesites.",
    "Tus metas son alcanzables con esfuerzo.",
    "Estudia para ti y para tu crecimiento.",
    "Cada hora invertida vale la pena.",
    "Celebra tus avances y sigue adelante.",
    "El conocimiento abre puertas inimaginables.",
    "Tu futuro se construye hoy con estudio.",
    "La constancia vence cualquier dificultad.",
    "Tú puedes con cada desafío académico.",
    "Confía en ti, eres capaz de lograrlo.",
    "Estudia con alegría y determinación.",
    "Cada paso académico es un paso hacia tus sueños.",
    "Aprender te hace más fuerte y sabio.",
    "Sigue adelante, no te rindas.",
    "Tu esfuerzo hoy cambia tu mañana.",
    "El éxito académico es fruto del trabajo diario."
  ],
  cansado: [
    "El descanso es tan importante como el esfuerzo, tómate tu tiempo para recargar.",
    "Cada paso que das, aunque cansado, te acerca a tu meta.",
    "El cansancio es señal de que estás trabajando por tus sueños.",
    "Permítete una pausa, tu cuerpo y mente te lo agradecerán.",
    "Recargar energías es avanzar con más fuerza.",
    "No te juzgues por necesitar descanso.",
    "El autocuidado es fundamental para tu éxito.",
    "Escucha a tu cuerpo y respeta sus señales.",
    "La pausa es parte del proceso de crecimiento.",
    "Dormir bien renueva tu espíritu y mente.",
    "El cansancio no es debilidad, es humanidad.",
    "Date permiso para recuperar fuerzas.",
    "La paciencia contigo mismo es vital.",
    "Eres fuerte, pero también necesitas cuidarte.",
    "El descanso te prepara para nuevos retos.",
    "No todo es productividad, también es bienestar.",
    "Recuerda que avanzar no siempre es ir rápido.",
    "El equilibrio entre esfuerzo y descanso es clave.",
    "Cada descanso te hace más eficiente.",
    "Sigue adelante con calma y seguridad.",
    "Tu salud es tu mayor tesoro.",
    "No te exijas más de lo que puedes dar hoy.",
    "Eres valioso, aunque te sientas agotado.",
    "Aprende a desconectar para reconectar.",
    "Cuidarte es amarte a ti mismo.",
    "Un respiro es un acto de amor propio.",
    "El descanso fortalece tu resistencia.",
    "No hay victoria sin momentos de calma.",
    "Tómate tiempo para ti sin culpa.",
    "La recuperación es parte del éxito.",
    "Tu cuerpo merece respeto y cuidado.",
    "Sigue avanzando, pero sin agotarte.",
    "Cada día es una oportunidad para renovarte.",
    "La fatiga no es derrota, es señal de esfuerzo.",
    "El descanso mejora tu rendimiento.",
    "Aprende a priorizar tu bienestar.",
    "Eres un guerrero que sabe cuándo parar.",
    "La tranquilidad también es productividad.",
    "Cuida tu mente con pausas saludables.",
    "No estás solo en tu cansancio.",
    "Agradece lo que has logrado hasta ahora.",
    "Cada día es un nuevo comienzo.",
    "El autocuidado es clave para tu felicidad.",
    "Sigue caminando, pero con amor propio.",
    "No te rindas, solo descansa.",
    "Las pequeñas pausas hacen grandes cambios.",
    "Confía en el proceso de recuperación.",
    "La paciencia contigo te hace invencible.",
    "Eres más fuerte que tu cansancio.",
    "Siente orgullo por avanzar a pesar del agotamiento."
  ],
  motivado: [
    "Sigue adelante, tu esfuerzo pronto dará frutos.",
    "La motivación es el combustible para lograr lo imposible.",
    "Tu pasión hoy construye tu éxito mañana.",
    "Cada paso te acerca más a tus sueños.",
    "Confía en ti y en tu capacidad de lograrlo.",
    "No dejes que nada detenga tu impulso.",
    "El camino al éxito está hecho de constancia.",
    "Tú tienes el poder de cambiar tu historia.",
    "Cree en ti y en tu potencial ilimitado.",
    "Las metas grandes comienzan con pequeños pasos.",
    "Cada día es una oportunidad para avanzar.",
    "No temas desafiar tus propios límites.",
    "La disciplina es tu mejor aliada.",
    "El esfuerzo de hoy es la recompensa del mañana.",
    "Sigue soñando y trabaja con pasión.",
    "La perseverancia rompe cualquier obstáculo.",
    "Eres capaz de lograr lo que te propongas.",
    "No te detengas hasta estar orgulloso.",
    "El éxito es para quienes no se rinden.",
    "Tu motivación contagia a quienes te rodean.",
    "Trabaja duro y celebra tus logros.",
    "Cada fracaso es una lección para crecer.",
    "Mantén viva la llama de tu entusiasmo.",
    "Visualiza tu triunfo y trabaja por él.",
    "No esperes, crea tu propio momento perfecto.",
    "Cada esfuerzo te hace más fuerte.",
    "Tu pasión es tu mejor motor.",
    "Confía en el proceso y en ti mismo.",
    "Sigue adelante con energía y foco.",
    "Nada es imposible para quien persevera.",
    "La motivación se renueva con cada acción.",
    "Tu actitud define tu camino.",
    "Hazlo con ganas o no lo hagas.",
    "Cada día cuenta para tu meta.",
    "Construye hábitos que te impulsen.",
    "Eres un guerrero en constante evolución.",
    "Tu esfuerzo cambiará tu realidad.",
    "La grandeza está dentro de ti.",
    "Persiste y alcanzarás la cima.",
    "El éxito es la suma de pequeños pasos.",
    "No te rindas, cada intento vale.",
    "Tú defines tu propio destino.",
    "Aprovecha tu energía para crear.",
    "Sigue luchando, el premio llegará.",
    "El compromiso contigo es fundamental.",
    "Celebra cada logro, por pequeño que sea.",
    "La motivación te lleva más lejos que el talento.",
    "Tú puedes, solo cree en ti.",
    "El presente es tu mejor oportunidad."
  ],
  duelo: ["Aunque hoy te sientas pesado, recuerda que la luz volverá.",
    "Cada pequeño paso es un gran avance.",
    "No estás solo, hay apoyo y comprensión.",
    "Tu valor no depende de tu estado emocional.",
    "Permítete sentir sin juzgarte.",
    "Hablar ayuda a aliviar la carga interior.",
    "Eres más fuerte que cualquier tristeza.",
    "La esperanza es una semilla que nunca muere.",
    "Busca momentos que te hagan sonreír.",
    "Cada día es una oportunidad para renacer.",
    "Tu vida importa, aunque no lo sientas ahora.",
    "El descanso es parte importante de la recuperación.",
    "No temas pedir ayuda cuando la necesites.",
    "La oscuridad es temporal, la luz siempre vuelve.",
    "Permítete sanar a tu ritmo.",
    "Eres importante y digno de amor.",
    "Cada esfuerzo por seguir adelante cuenta.",
    "Confía en que los malos momentos pasarán.",
    "Pequeñas victorias fortalecen tu espíritu.",
    "La sanación comienza con el amor propio.",
    "No te castigues por lo que sientes.",
    "Busca belleza en los pequeños detalles.",
    "Cada día trae nuevas esperanzas.",
    "No estás definido por tu tristeza.",
    "La luz puede encontrarse en la oscuridad.",
    "Respira y recuerda que puedes seguir.",
    "Tu historia aún no ha terminado.",
    "Eres valiente por continuar luchando.",
    "La vida tiene sorpresas buenas para ti.",
    "Cada paso hacia adelante es un triunfo.",
    "Tu mente merece cuidado y compasión.",
    "Permítete momentos de alegría cuando puedas.",
    "Eres capaz de superar esta etapa.",
    "Cada amanecer trae nuevas oportunidades.",
    "No pierdas la fe en ti mismo.",
    "El amor propio es la mejor medicina.",
    "Busca apoyo en quienes te quieren.",
    "El dolor no es el final, es un comienzo.",
    "Eres digno de felicidad y paz.",
    "No estás solo en esta lucha.",
    "Cada pequeño esfuerzo es valioso.",
    "El tiempo ayuda a sanar heridas.",
    "Permítete descansar sin culpa.",
    "Confía en tu fuerza interior.",
    "Tu valor es inmenso y verdadero.",
    "Sigue adelante con esperanza y coraje.",
    "La vida puede sorprenderte de nuevo.",
    "Eres un ser valioso y amado.",
    "Cada día es un nuevo comienzo.",
    "Tú puedes, paso a paso."
  ],
   estudios: [
    "Estudiar hoy es construir el futuro que deseas.",
    "Cada página que lees te acerca a tus sueños.",
    "El esfuerzo que haces ahora será tu recompensa mañana.",
    "Tu éxito empieza con un poco de disciplina.",
    "No dejes para mañana lo que puede abrirte puertas hoy.",
    "Un poco de estudio diario hace grandes cambios.",
    "Los sacrificios de hoy son las victorias del mañana.",
    "Cada minuto de estudio es una inversión en ti.",
    "No es fácil, pero tu futuro vale la pena.",
    "Estudiar te da el poder de cambiar tu destino.",
    "La constancia es la clave para lograr lo que quieres.",
    "Aprender es la mejor herramienta para la libertad.",
    "Aunque cueste, el conocimiento es tu mejor aliado.",
    "Cada esfuerzo cuenta para ser mejor cada día.",
    "Las metas grandes requieren trabajo constante.",
    "Piensa en la satisfacción de lograr tus objetivos.",
    "El éxito pertenece a quienes no se rinden.",
    "Tu mente es un músculo, ¡hay que entrenarla!",
    "Lo que hoy parece difícil, mañana será rutina.",
    "El camino al éxito pasa por la perseverancia.",
    "No te enfoques en lo que cuesta, sino en lo que ganas.",
    "Cada hora estudiada es un paso hacia tu sueño.",
    "Los que triunfan son los que siguen adelante.",
    "No esperes motivación, créala con disciplina.",
    "No es cuestión de ganas, es cuestión de actitud.",
    "Estudiar abre puertas que otros ni siquiera ven.",
    "El esfuerzo de ahora te hará libre en el futuro.",
    "No te detengas, cada día cuenta para tu éxito.",
    "La única forma de fracasar es no intentarlo.",
    "Transforma la pereza en acción y progreso.",
    "Visualiza tu futuro y trabaja para conseguirlo.",
    "Cada pequeño avance te acerca a tu meta.",
    "La educación es el arma más poderosa que tienes.",
    "Sé más fuerte que tus excusas.",
    "No pospongas tu éxito, empieza hoy.",
    "Tu futuro yo te agradecerá este esfuerzo.",
    "El tiempo que inviertes en estudiar no es tiempo perdido.",
    "El sacrificio de hoy será tu orgullo mañana.",
    "No estudias para el examen, estudias para la vida.",
    "Los grandes logros comienzan con pequeños esfuerzos.",
    "No permitas que la flojera te robe tus sueños.",
    "Sigue adelante aunque no tengas ganas.",
    "El conocimiento es la base del poder.",
    "Eres capaz de lograr todo lo que te propongas.",
    "Cada día que estudias, estás un paso más cerca.",
    "No te rindas, tu esfuerzo valdrá la pena.",
    "La disciplina hoy es la libertad mañana.",
    "No hay límites para quien se esfuerza.",
    "Hazlo por ti, por tus sueños y tu futuro.",
    "La motivación viene con la acción, ¡empieza ya!",
    "Tu sacrificio actual construye tu camino."
  ],
  trabajo: [
    "Cada esfuerzo en tu trabajo suma para tu éxito.",
    "Sé constante y el éxito llegará.",
    "Tu dedicación es el camino a la excelencia.",
    "En el trabajo, la perseverancia es clave.",
    "Confía en tus capacidades profesionales.",
    "Cada día es una nueva oportunidad laboral.",
    "Tu actitud define tu crecimiento en el trabajo.",
    "Aprende de cada experiencia laboral.",
    "El esfuerzo constante mejora tus habilidades.",
    "No temas asumir nuevos retos laborales.",
    "El trabajo bien hecho siempre es reconocido.",
    "Cada proyecto es una oportunidad para crecer.",
    "Sé proactivo y marca la diferencia.",
    "El compromiso trae grandes recompensas.",
    "Tu pasión por lo que haces se nota y suma.",
    "Trabaja con entusiasmo y dedicación.",
    "El éxito laboral es fruto de la constancia.",
    "Valora tu tiempo y esfuerzo en el trabajo.",
    "Cada día laboral es una escuela de vida.",
    "Sigue aprendiendo y mejorando tus habilidades.",
    "La paciencia y el esfuerzo llevan lejos.",
    "Tu ética profesional es tu mejor carta.",
    "No te rindas ante los obstáculos laborales.",
    "Eres capaz de superar cualquier desafío.",
    "Mantén una actitud positiva en el trabajo.",
    "Cada meta laboral es alcanzable con esfuerzo.",
    "La disciplina en el trabajo trae éxito.",
    "Aprovecha cada oportunidad para crecer.",
    "Tu trabajo aporta valor y propósito.",
    "Confía en tu talento y capacidad.",
    "Los logros laborales construyen tu futuro.",
    "Sé un ejemplo de profesionalismo.",
    "Trabaja con pasión y compromiso.",
    "La perseverancia es tu mejor aliada.",
    "Celebra cada logro profesional.",
    "Aprende de tus errores y sigue adelante.",
    "El crecimiento laboral es un proceso constante.",
    "Tu esfuerzo hará la diferencia.",
    "No temas salir de tu zona de confort.",
    "Tu trabajo habla de ti, hazlo bien.",
    "Sé resiliente ante las dificultades laborales.",
    "El éxito es resultado de trabajo duro y enfoque.",
    "Mantén la motivación cada día.",
    "Cada experiencia laboral te fortalece.",
    "Confía en tu capacidad para alcanzar tus metas.",
    "La pasión por tu trabajo te impulsa.",
    "Sé constante y paciente con tu crecimiento.",
    "Cada día es una oportunidad para mejorar.",
    "Tú puedes lograr lo que te propongas.",
    "El trabajo con sentido da satisfacción.",
    "La dedicación te abrirá muchas puertas.",
    "No dejes de aprender y superarte.",
    "El compromiso con tu trabajo es clave."
  ],
  relaciones: [
    "Las relaciones saludables se construyen con respeto y comunicación.",
    "Escuchar es tan importante como hablar en una relación.",
    "El amor propio es la base para relaciones sanas.",
    "Permítete poner límites claros y amorosos.",
    "Las relaciones auténticas nutren el alma.",
    "Aprende a perdonar para liberar tu corazón.",
    "El respeto mutuo fortalece cualquier relación.",
    "Cultiva la empatía y la comprensión.",
    "La confianza es el pilar fundamental del amor.",
    "Comunica tus necesidades con sinceridad.",
    "Valora a quienes te apoyan y quieren bien.",
    "No temas alejarte de relaciones tóxicas.",
    "Cada relación es una oportunidad de aprendizaje.",
    "El amor verdadero no lastima, sana.",
    "Construye relaciones basadas en la honestidad.",
    "Escucha con el corazón y no solo con los oídos.",
    "El diálogo abierto mejora la convivencia.",
    "El respeto comienza por respetarte a ti mismo.",
    "Agradece a quienes te acompañan en el camino.",
    "Aprende a dar y recibir con equilibrio.",
    "Las relaciones sanas impulsan tu crecimiento personal.",
    "Sé paciente y compasivo con los demás.",
    "Aprende a expresar tus emociones en pareja.",
    "Construir confianza requiere tiempo y esfuerzo.",
    "No te conformes con menos de lo que mereces.",
    "El amor propio te protege de relaciones dañinas.",
    "La sinceridad abre puertas a la cercanía.",
    "Cultiva la amistad y el apoyo mutuo.",
    "Aprecia la diversidad en tus relaciones.",
    "El perdón libera y fortalece el corazón.",
    "Cada persona aporta algo valioso a tu vida.",
    "Valora la comunicación clara y respetuosa.",
    "No temas mostrarte tal cual eres.",
    "El respeto mutuo genera armonía.",
    "Aprende a escuchar sin juzgar.",
    "Cultiva la gratitud en tus relaciones.",
    "Las relaciones profundas son tesoros para la vida.",
    "Busca relaciones que te hagan crecer y brillar.",
    "El amor sano es libre y generoso.",
    "Confía en el proceso de construir relaciones.",
    "Sé un buen amigo y compañero.",
    "No temas pedir ayuda en tus relaciones.",
    "Aprende a soltar lo que no te hace bien.",
    "El amor comienza por amarte a ti mismo.",
    "Cada encuentro es una oportunidad para amar.",
    "Respeta tus emociones y las de los demás.",
    "La comunicación es el corazón de las relaciones.",
    "Aprende a construir vínculos saludables.",
    "El amor genuino es paciente y amable.",
    "Valora el tiempo compartido con quienes amas."
  ],
  emociones: [
    "Tus emociones son señales que te ayudan a entenderte.",
    "Permítete sentir sin juzgar tus emociones.",
    "Cada emoción tiene un mensaje para ti.",
    "Aceptar tus emociones es el primer paso para manejarlas.",
    "La calma llega cuando reconoces lo que sientes.",
    "Tus emociones te conectan con tu verdad interior.",
    "Hablar de tus emociones libera tu mente.",
    "No reprimas lo que sientes, exprésalo con respeto.",
    "Cada emoción es parte de tu humanidad.",
    "El autocuidado incluye escuchar tus emociones.",
    "Aprende a identificar tus emociones para manejarlas mejor.",
    "La inteligencia emocional mejora tu bienestar.",
    "Tus emociones te guían hacia lo que necesitas.",
    "Permítete espacio para procesar tus sentimientos.",
    "No estás definido por una sola emoción.",
    "La empatía empieza con entender tus propias emociones.",
    "El equilibrio emocional es posible con práctica.",
    "Tus emociones cambian y eso es normal.",
    "Respira y observa tus emociones sin miedo.",
    "La aceptación emocional es sanadora.",
    "Expresar tus emociones te libera y fortalece.",
    "No te castigues por sentir lo que sientes.",
    "Tus emociones son válidas siempre.",
    "El autoconocimiento nace de conectar con tus emociones.",
    "Practica la compasión contigo mismo.",
    "Aprende a transformar emociones negativas en energía positiva.",
    "Tus emociones te dan información valiosa.",
    "El equilibrio emocional es una meta alcanzable.",
    "Confía en tu capacidad para gestionar tus emociones.",
    "El amor propio incluye aceptar tus emociones.",
    "Cada emoción tiene su tiempo y espacio.",
    "No temas pedir ayuda para manejar tus emociones.",
    "El respeto hacia tus emociones es fundamental.",
    "Cada día es una oportunidad para entenderte mejor.",
    "Las emociones intensas pasan, la calma vuelve.",
    "La práctica constante mejora tu inteligencia emocional.",
    "Permítete momentos para reflexionar sobre tus emociones.",
    "Tus emociones te conectan con los demás.",
    "El autocuidado emocional es un acto de valentía.",
    "Cultiva pensamientos que apoyen tu bienestar emocional.",
    "No estás solo en tu experiencia emocional.",
    "La paciencia contigo mismo fortalece tu salud emocional.",
    "Acepta tus emociones para vivir con autenticidad.",
    "Aprende a soltar lo que no puedes controlar.",
    "Cada emoción vivida te hace crecer.",
    "Busca la belleza incluso en las emociones difíciles.",
    "Tu equilibrio emocional es un regalo para ti.",
    "La serenidad llega con la práctica diaria.",
    "Celebra tus avances emocionales.",
    "Eres un ser emocionalmente fuerte y valioso."
  ],
  crecimiento_personal: [
    "El crecimiento personal comienza con la voluntad de cambiar.",
    "Cada día es una oportunidad para ser mejor.",
    "Aprende de tus errores y sigue adelante.",
    "La autoconciencia es la clave del desarrollo.",
    "Confía en tu capacidad para transformar tu vida.",
    "La disciplina te lleva a nuevas alturas.",
    "Acepta los desafíos como oportunidades de aprendizaje.",
    "Cada pequeño avance es un gran logro.",
    "El amor propio impulsa tu crecimiento.",
    "No temas salir de tu zona de confort.",
    "El cambio comienza con un solo paso.",
    "Celebra tus progresos sin importar su tamaño.",
    "Sé paciente contigo mismo en el proceso.",
    "Cada experiencia te hace más sabio.",
    "La resiliencia es una habilidad que se aprende.",
    "La mente abierta facilita el crecimiento.",
    "Aprende a soltar lo que te limita.",
    "El autoconocimiento fortalece tu autoestima.",
    "Mantén una actitud positiva ante la vida.",
    "El crecimiento personal es un viaje continuo.",
    "Confía en tu intuición y sabiduría interior.",
    "El aprendizaje constante es vital para crecer.",
    "Los retos fortalecen tu carácter.",
    "Cuida tu mente, cuerpo y espíritu.",
    "Sé amable contigo mismo en cada paso.",
    "El crecimiento nace del compromiso contigo.",
    "Desarrolla hábitos que apoyen tu bienestar.",
    "Cada día trae nuevas oportunidades para crecer.",
    "Abraza el cambio con valentía.",
    "La autocompasión es parte del crecimiento.",
    "Cultiva la gratitud por tu proceso.",
    "El crecimiento personal te lleva a la libertad.",
    "Aprende a perdonarte y seguir adelante.",
    "Mantén la motivación en tus metas.",
    "El cambio verdadero viene desde dentro.",
    "No te compares, cada camino es único.",
    "El autodescubrimiento es un regalo.",
    "Invierte tiempo en tu desarrollo personal.",
    "Confía en el proceso de transformación.",
    "La constancia es la clave del éxito.",
    "Eres capaz de crear la vida que deseas.",
    "El crecimiento personal mejora todas tus relaciones.",
    "Cada paso te acerca a tu mejor versión.",
    "Aprende a escuchar tu voz interior.",
    "El amor propio es la base de todo cambio.",
    "Sé tu propio motor de transformación.",
    "El crecimiento personal es liberador.",
    "Celebra tu evolución con orgullo.",
    "Sigue avanzando con pasión y coraje.",
    "Tu mejor versión está en camino."
  ],
  deporte: [
    "El esfuerzo constante te lleva a la excelencia deportiva.",
    "Cada entrenamiento te hace más fuerte y resistente.",
    "La disciplina es la clave para alcanzar tus metas.",
    "Siente la satisfacción de superar tus límites.",
    "El deporte fortalece cuerpo, mente y espíritu.",
    "No te rindas ante las dificultades, persiste.",
    "La constancia es tu mejor aliada en el deporte.",
    "Celebra cada pequeño avance en tu rendimiento.",
    "Entrena con pasión y dedicación.",
    "El éxito deportivo nace del trabajo diario.",
    "Tu cuerpo es capaz de lograr grandes cosas.",
    "Disfruta del proceso, no solo del resultado.",
    "El deporte te enseña paciencia y perseverancia.",
    "Confía en tu preparación y esfuerzo.",
    "Cada desafío deportivo es una oportunidad para crecer.",
    "La motivación te impulsa a seguir adelante.",
    "Cuida tu cuerpo con alimentación y descanso.",
    "El deporte mejora tu salud y bienestar general.",
    "Siente orgullo por cada meta alcanzada.",
    "La actitud positiva potencia tu rendimiento.",
    "Supera tus límites con determinación.",
    "El deporte es una forma de amor propio.",
    "Aprende de cada error y sigue entrenando.",
    "Tu cuerpo es tu mejor herramienta.",
    "La fuerza mental es tan importante como la física.",
    "El trabajo en equipo fortalece el espíritu deportivo.",
    "No te compares con otros, solo contigo mismo.",
    "La constancia vence cualquier obstáculo.",
    "Celebra la alegría de moverte y entrenar.",
    "El esfuerzo diario crea grandes campeones.",
    "Mantén la motivación alta en todo momento.",
    "El deporte es un camino hacia la superación personal.",
    "Confía en tu capacidad para alcanzar tus objetivos.",
    "Cada día es una oportunidad para mejorar.",
    "El entrenamiento es la base del éxito.",
    "Cuida tu mente y cuerpo con equilibrio.",
    "El deporte te enseña disciplina y respeto.",
    "La pasión por el deporte te llevará lejos.",
    "Sigue adelante con energía y entusiasmo.",
    "Celebra cada logro con gratitud.",
    "Aprende a disfrutar cada entrenamiento.",
    "Tu esfuerzo es un ejemplo para otros.",
    "El deporte fortalece tu confianza y autoestima.",
    "No temas desafiar tus propios límites.",
    "El camino deportivo es una aventura maravillosa.",
    "Sigue creciendo y superándote cada día.",
    "Eres un campeón en constante evolución.",
    "El deporte es salud, alegría y vida.",
    "Disfruta del viaje y no solo del destino.",
    "Tu compromiso deportivo vale la pena.",
    "Sigue entrenando con pasión y corazón."
  ],
  hueso_ancho: ["Tu fuerza está en aceptarte tal como eres.",
  "Eres una fortaleza, no una disculpa.",
  "El valor no tiene talla ni forma.",
  "Tu cuerpo es un templo que merece amor.",
  "La confianza es tu mejor vestido.",
  "Tu autenticidad es tu mayor belleza.",
  "Cada paso seguro reafirma tu valor.",
  "No necesitas encajar, naciste para destacar.",
  "Eres digno/a exactamente como eres.",
  "Celebra tu cuerpo, es tu hogar.",
  "Eres inspiración para muchos sin saberlo.",
  "La verdadera belleza es la autenticidad.",
  "Sé orgulloso/a de tu esencia única.",
  "Tu presencia llena cualquier espacio.",
  "La aceptación propia es el primer triunfo.",
  "Tu cuerpo cuenta una historia de fuerza.",
  "La confianza rompe cualquier estándar.",
  "Eres suficiente y mereces lo mejor.",
  "La belleza real no cabe en etiquetas.",
  "Camina con seguridad, impactas con tu luz.",
  "Eres más fuerte que cualquier opinión ajena.",
  "Tu cuerpo es tu aliado, cuídalo y ámalo.",
  "No te compares, brilla con tu luz propia.",
  "Cada día reafirmas tu valor interior.",
  "El amor propio transforma cualquier inseguridad.",
  "Tu esencia es tu superpoder.",
  "Sé la mejor versión de ti sin excusas.",
  "La aceptación abre puertas a la felicidad.",
  "El respeto comienza contigo mismo/a.",
  "Eres único/a, no necesitas aprobación.",
  "La confianza es más atractiva que cualquier físico.",
  "Ama tu cuerpo, es el vehículo de tu vida.",
  "Tu tamaño no limita tu grandeza.",
  "La autoestima es la armadura del alma.",
  "Eres digno/a de amor sin condiciones.",
  "La felicidad nace del amor propio.",
  "Celebra tus diferencias, ellas te hacen especial.",
  "Tu valor es inmenso e inquebrantable.",
  "Nadie puede definir tu valía excepto tú.",
  "El amor propio es tu mejor revolución.",
  "Tu cuerpo refleja la historia de tu vida.",
  "Camina con orgullo y autenticidad siempre.",
  "El respeto empieza por aceptarte a ti mismo.",
  "Eres fuerte, valiente y único/a.",
  "Tu belleza está en tu confianza y alegría.",
  "No necesitas cambiar para ser amado.",
  "El poder de tu esencia transforma todo.",
  "Eres digno/a de respeto y felicidad.",
  "Tu cuerpo es una obra de arte viviente.",
  "Ama cada curva, cada línea, cada parte.",
  "Confía en ti, eres más de lo que imaginas."],
  deprimido: ["Aunque hoy parezca gris, el sol volverá a brillar.",
  "Tu existencia tiene un valor inmenso.",
  "Respira, sobrevivir es un acto de valentía.",
  "No estás solo/a, hay quienes te apoyan.",
  "Cada pequeño paso es una gran victoria.",
  "Permítete sanar a tu ritmo, sin presiones.",
  "El dolor es temporal, la esperanza es eterna.",
  "Eres más fuerte de lo que crees.",
  "No temas pedir ayuda cuando la necesites.",
  "Cada día es una nueva oportunidad para empezar.",
  "Tu luz interior nunca se apaga completamente.",
  "No te juzgues por cómo te sientes hoy.",
  "El descanso es parte de la recuperación.",
  "Hablar libera y aligera el alma.",
  "Tu valor no depende de tu estado emocional.",
  "Permítete sentir sin culpa ni miedo.",
  "Eres importante, incluso cuando no lo sientes.",
  "Confía en que esta etapa también pasará.",
  "Tu vida tiene un propósito único y valioso.",
  "Los momentos difíciles enseñan grandes lecciones.",
  "Busca la belleza en las pequeñas cosas.",
  "La esperanza puede estar escondida, pero está ahí.",
  "Cada esfuerzo cuenta, aunque parezca poco.",
  "No estás roto/a, estás en proceso de sanar.",
  "El amor propio es la base para sanar.",
  "Permite que la calma te envuelva poco a poco.",
  "La oscuridad no puede con la luz eterna dentro de ti.",
  "Tienes el poder de transformar tu historia.",
  "El sol siempre vuelve a salir después de la tormenta.",
  "Eres digno/a de amor y felicidad.",
  "No tienes que hacerlo todo solo/a.",
  "El autocuidado es un acto de valentía.",
  "Cada día te acercas más a la paz interior.",
  "La depresión no define quién eres realmente.",
  "La paciencia contigo mismo/a es fundamental.",
  "La vida puede sorprenderte con nuevas esperanzas.",
  "Tus emociones son válidas y merecen respeto.",
  "El primer paso hacia la sanación es reconocer el dolor.",
  "Tú importas, incluso cuando te cuesta creerlo.",
  "Confía en que puedes superar esta etapa.",
  "No pierdas la fe en ti mismo/a.",
  "El tiempo es un aliado en tu recuperación.",
  "El amor de quienes te rodean te sostiene.",
  "No temas buscar apoyo profesional.",
  "La sanación es un camino, no una meta inmediata.",
  "Permítete momentos de alegría cuando puedas.",
  "Cada nuevo día es una nueva oportunidad.",
  "Eres fuerte, incluso en los días más difíciles.",
  "Nunca estás completamente solo/a.",
  "Cuida tu mente con el mismo amor que cuidas tu cuerpo.",
  "El cambio es posible, paso a paso."]
};

let ultimaCategoria = "";
let ultimaFrase = "";

function mostrarFraseCategoria() {
  const selectBasico = document.getElementById("emocion-basica");
  const selectCategoria = document.getElementById("categoria");

  const categoria = selectBasico.value || selectCategoria.value;
  const fraseContenedor = document.getElementById("frase");

  if (!categoria || !frases[categoria] || frases[categoria].length === 0) {
    fraseContenedor.textContent = "Por favor, selecciona una emoción o categoría válida.";
    return;
  }

  const lista = frases[categoria];
  const nuevaFrase = lista[Math.floor(Math.random() * lista.length)];

  fraseContenedor.textContent = nuevaFrase;
  ultimaCategoria = categoria;
  ultimaFrase = nuevaFrase;

  // Lista de todas las clases posibles para emociones/categorías
  const clases = [
    "triste", "feliz", "estresado", "sorpresa", "cansado", "motivado", "duelo",
    "estudios", "trabajo", "emociones", "relaciones", "crecimiento_personal",
    "deporte", "hueso_ancho", "deprimido"
  ];

  // Eliminar todas las clases de emoción antes de añadir la nueva
  clases.forEach(c => document.body.classList.remove(c));

  // Añadir la clase que corresponde a la categoría seleccionada para cambiar el fondo
  document.body.classList.add(categoria);

  // Mostrar el botón para pedir otra frase
  document.getElementById("btn-otra-cat").style.display = "inline-block";
}

function otraFraseCategoria() {
  if (!ultimaCategoria || !frases[ultimaCategoria]) return;

  let nuevaFrase;
  do {
    nuevaFrase = frases[ultimaCategoria][Math.floor(Math.random() * frases[ultimaCategoria].length)];
  } while (nuevaFrase === ultimaFrase && frases[ultimaCategoria].length > 1);

  document.getElementById("frase").textContent = nuevaFrase;
  ultimaFrase = nuevaFrase;
}

document.addEventListener("DOMContentLoaded", () => {
  const btnFrase = document.getElementById("btn-frase");
  const btnOtra = document.getElementById("btn-otra-cat");

  if (btnFrase && btnOtra) {
    btnFrase.addEventListener("click", mostrarFraseCategoria);
    btnOtra.addEventListener("click", otraFraseCategoria);
  } else {
    console.error("No se encontraron los botones necesarios.");
  }
});
